{% set name = "grib2io" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grib2io-{{ version }}.tar.gz
  sha256: b50b3150661ebb642b19a70a585fbcaa3d52d985c5c4d34371d3011634f4a383

build:
  skip: true  # [win or py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0
  host:
    - python
    - cython >=0.29.16
    - setuptools >=61.0
    - numpy
    - pip
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0
  run:
    - python
    - pyproj
    - nceplibs-g2c
    - nceplibs-ip >=5.1.0

test:
  imports:
    - grib2io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NOAA-MDL/grib2io
  summary: Python interface to the NCEP G2C Library for reading/writing GRIB2 files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
